#!/usr/bin/env bash

set -eo pipefail

KALLITHEA_HOMEDIR=$OPENSHIFT_DATA_DIR/kallithea-runtime

mkdir -p $KALLITHEA_HOMEDIR
cd $KALLITHEA_HOMEDIR

if ! test -f production.ini; then
    paster make-config Kallithea production.ini

    touch database_setup_required

    sed -i.bak "s/^debug = true/debug = false/" production.ini
    sed -i.bak "s/^use_celery = .*$/use_celery = false/" production.ini
    sed -i.bak "s%^git_path = .*$%git_path = `which git`%" production.ini

    cat production.ini
fi
