#!/bin/bash
# start kallithea

ROOT=$OPENSHIFT_DATA_DIR
CONF_NAME="/kallithea/production.ini"
PID_PATH="$ROOT/kallithea/kallithea.pid"
LOG_PATH="$ROOT/kallithea/kallithea.log"

source $ROOT/kallithea-venv/bin/activate

cd $ROOT/kallithea
if [ -f $ROOT/kallithea/install ]
then
  paster setup-kallithea production.ini --user="admin" --password="changethis" --email="admin@test.com" --repos="$ROOT/kallithea/repos" --force-yes
  echo ">>>>>>>>>>>>>>>>>>>"
  echo "user: admin"
  echo "pass: changethis"
  echo ">>>>>>>>>>>>>>>>>>>"
  rm $ROOT/kallithea/install
else
  paster upgrade-db production.ini --force-yes
fi

PYTHON_EGG_CACHE="/tmp" $ROOT/kallithea-venv/bin/paster serve --daemon \
  --user=$USER \
  --group=$USER \
  --pid-file=$PID_PATH \
  --log-file=$LOG_PATH \
  $ROOT/$CONF_NAME

